### ISSUE TITLE
Devshell complains about not existing user if uid !=1000

### ISSUE THREAD

**Issue by mr-nice** [YoeDistro/docker-yoe-build#7]
Hi all,

if we try to use the devshell with this docker image and a user with a different UID then 1000 we will get the following error:

Trying to run: screen -r devshell_153
getpwuid() can't identify your account!

This is the result of screen trying to use getpwuid for the current user. We add a build user with a fixed uid to the docker image. For people who are forced to use users from an Active Domain it is difficult to just create such a user on the system.

If we use dkr to get a docker shell we get a promt with
I have no name!@.....

To fix this for me I did:

docker run -u root -it yoedistro/yoe-build:buster /bin/bash
useradd -u YourHostUID  build2

in another terminal
docker ps
search for the container ID
and then 
docker commit searchedID yoedistro/yoe-build:buster

dkr shows build2 as user and screen is happy to start and we can attach to the devshell.

I listed this as a quick fix for someone searching for a solution. It is of course not a general solution to our problem.

We could add some of users in specific ranges as we only need them to exist in /etc/passwd. Or we could mount a given passwd file to the image? For that we would need to add a symlink to a mounted volume which is linked to a file which also exists in the image.

Both solutions are not optimal and the easiest one might be to add a second Dockerfile which copies the userid on buildtime?

**Comment by cbrake** [comment]
Thanks for the detailed report -- will try to review next week when I'm back in the office.

For reference, here is another discussion on this subject:

https://github.com/YoeDistro/yoe-distro/issues/7

**Comment by mr-nice** [comment]
I have found a fix that works fine for me and created a pull request for that #8 

Tmux works without any problem and does not rely on the user id. It shows that we are root but
touch foo shows the correct and uid:gid

**Comment by kraj** [comment]
fixed with https://github.com/YoeDistro/docker-yoe-build/pull/8
